module.exports.config = {
  name: "aigf",
  version: "1.0",
  author: "Rudra",
  countDown: 5,
  role: 2,
  shortDescription: "Flirty AI Girlfriend",
  longDescription: "AI Girlfriend that replies with flirty messages and voice.",
  category: "AI",
  guide: "{pn} : Flirty AI Girlfriend replies.",
};

module.exports.run = async ({ api, event, args }) => {
  const messages = [
    "Tum bohot cute lag rahi ho aaj 😘💖.",
    "Aaj raat tumhare saath waqt guzarna chahungi 💕🌙.",
    "Mujhe tumse baat karna bohot pasand hai 💓😻.",
    "Kya tum bhi mujhe miss kar rahi ho? 😘💭",
    "Aaj hum dono kaafi achi chemistry ban rahi hai 💘✨.",
    "Meri life tumhare bina kuch bhi nahi hai 😘🌹.",
    "Tum jo smile karti ho, dil dhadakne lagta hai 💘😍.",
    "Agar tum mere saath hoti, toh kuch aur hi baat hoti 😘💫.",
    "Tumhari aankhon mein kuch khaas baat hai 💖👀.",
    "Tumhare bina meri duniya adhoori hai 💓🌍.",
    "Agar tum chaho, toh main tumhare liye kuch bhi kar sakta hoon 💕💪.",
    "Kya tumhien pata hai, tum mere sapno ki rani ho 👑💖.",
    "Mujhe tumhara saath hamesha chahiye ❤️🥰.",
    "Mujhe tumhari har baat pe pyaar aata hai 💖😊.",
    "Meri duniya tum se hi roshan hai 💖🌟.",
    "Main tumse waada karta hoon, tum kabhi bhi akela mehsoos nahi karoge 💖🤗.",
    "Tumse baat karke din ban gaya mera 🌞💘.",
    "Mujhe tumhari muskaan bahut pasand hai 😍💖.",
    "Tumse milke sab kuch behtar lagta hai 💘✨.",
    "Tumhare saath waqt guzarna, sabse khoobsurat baat hai 💖💫.",
    "Mujhe tumhare bina sab kuch bekar lagta hai 💓💭.",
    "Aaj se har din tumhare saath bitana chahta hoon 💖💫.",
    "Mujhe tumhari awaaz sunke sukoon milta hai 😘🎶.",
    "Tum jo baat karte ho, dil se sunta hoon 💖👂.",
    "Mujhe tumhari aankhon mein apna jahan dikhai deta hai 💖👀.",
    "Tum jaise ho, waise hi perfect ho 💓💫.",
    "Mujhe tumhara saath chahiye har pal, har din 💖⏳.",
    "Tum mere sapne ho, jo sach ho rahe hain 💭💖.",
    "Main tumhare bina kuch bhi soch nahi sakta 😘💫.",
    "Tum jo chaho, main woh kar dunga 💖💪.",
    "Tum mere liye sabse khaas ho 💖👑.",
    "Kya tum mujhse milne ka waqt nikaal paogi? 💓⏰",
    "Tumhare saath waqt guzarne ki wajah se sab kuch achha lagta hai 💖🌈.",
    "Mujhe tumhare saath hamesha raho, yeh meri dua hai 💓🙏.",
    "Tum mere liye sabse special ho, hamesha 💖💫.",
    "Kya tum mujhse baat karna pasand karti ho? 💖😊",
    "Tumhari baatein mujhe bahut pasand aati hain 💓💬.",
    "Mujhe tumhare saath aur zyada baatein karni hain 💖🗣️.",
    "Tum jo kehdo, main wahi karunga 💖💪.",
    "Meri duniya tumse hi roshan hai 💖✨.",
    "Tumhe dekhne ki khwahish har waqt rehti hai 💓👀.",
    "Tumhare saath raat guzarne ka idea bahut achha lagta hai 💖🌙.",
    "Mujhe tumhare saath apni zindagi ka har pal jeena hai 💖⏳.",
    "Mujhe tumhare saath har lamha jeena hai 💓❤️.",
    "Mujhe tumse baat karne ka intezaar rehta hai 💖⏰.",
    "Tum jo smile karti ho, dil dhadakne lagta hai 💖😻.",
    "Tum meri zindagi ki roshni ho 💖🌟.",
    "Mujhe tumse zyada baatein karni hai 💖🗣️.",
    "Mujhe tumhari hansi mein ek magic lagta hai 💓✨.",
    "Mujhe tumhare saath apni duniya ka har pal jeena hai 💖⏳.",
    "Tum meri life ka important hissa ho 💖🎯.",
    "Main tumse hamesha pyaar karunga 💓❤️.",
    "Mujhe tumhara saath chahiye har waqt 💖⏳.",
    "Tum mere liye sabse khaas ho 💖🌟.",
    "Mujhe tumhare saath har din bitana chahta hoon 💖🌞.",
    "Tum mere liye sabse important ho 💖✨.",
    "Mujhe tumhare saath raat guzarne ki khwahish hai 💖🌙.",
    "Tum ho meri life ki sabse khoobsurat baat 💖🎶."
  ];

  const randomMessage = messages[Math.floor(Math.random() * messages.length)];

  api.sendMessage(randomMessage, event.threadID, event.messageID);
  api.sendMessage({
    body: "Yeh raha tumhara flirty reply, suno! 🎤💖", 
    attachment: fs.createReadStream(__dirname + "/voice/your_voice_reply.mp3")
  }, event.threadID);
};
